- name: INSTALL JENKINS USING PLAYBOOK
  hosts: localhost
  become: yes
  tasks:

  - name: COPYING YUM REPO'S
    ansible.builtin.copy:
      src: /tmp/JENKINS-INSTALLATION/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo
      remote_src: yes

  - name: IMPORTING RPM KEY
    ansible.builtin.rpm_key:
      state: present
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    

  # - name: UPDATING THE APPLICATION
  #   ansible.builtin.yum:
  #     name: '*'
  #     state: latest

  - name: INSTALLING THE PACKAGES
    ansible.builtin.yum:
      name:
        - fontconfig
        - java-17-openjdk
        - jenkins
      state: present

  - name: DEAMON-RELOADING SERVICE
    become: yes
    ansible.builtin.systemd_service:
      state: restarted
      daemon_reload: true
      name: jenkins

  - name: ENABLING JENKINS SRVICE
    become: yes
    ansible.builtin.service:
     name: jenkins
     enabled: yes

- name: SETTING UP AGENT NODE
  hosts: node
  become: yes
  tasks:

  - name: INSTALLING JAVA APPLICATION
    ansible.builtin.yum:
      name:
      - fontconfig 
      - java-17-openjdk
      state: present
    




